name: Test and Deploy

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hubのイメージ
        image: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Run bundle install
        run: |
          bundle install
      - name: Set up database schema
        run: bundle exec rails db:create
      - name: rspec test
        run: bundle exec rspec spec/requests/tasks_spec.rb
